# Generated by Django 2.1.3 on 2019-04-11 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0027_auto_20190411_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscriptos',
            name='institucion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Institucion'),
        ),
    ]
